name: Java CI/CD Pipeline

on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: wefly-app-jar
          path: target/WeFly_App_Final_Project.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/feature/transaction-api'

    steps:
      - uses: actions/checkout@v2
      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: wefly-app-jar
          path: target
      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Copy jar file to the server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key ./target/WeFly_App_Final_Project.jar root@${{ secrets.SERVER_IP }}:/root/synrgy
      - name: Execute deploy script
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key root@${{ secrets.SERVER_IP }} 'bash /root/synrgy/deploy_script.sh'

