name: Java CI/CD Pipeline

on:
  push:
    branches:
      - feature/transaction-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/feature/transaction-api'
    steps:
      - uses: actions/checkout@v2
      - name: Copy jar file to the server
        env: # Setting environment variables for a step
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          scp -i $SSH_PRIVATE_KEY ./target/WeFly_App_Final_Project.jar root@$SERVER_IP:/synrgy
      - name: Execute deploy script
        env: # Setting environment variables for a step
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -i $SSH_PRIVATE_KEY root@$SERVER_IP 'bash /synrgy/deploy_script.sh'
