name: Java CI/CD Pipeline

on:
  push:
    branches:
      - feature/transaction-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/feature/transaction-api'
    steps:
      - uses: actions/checkout@v2
      - name: Copy jar file to the server
        run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} ./target/WeFly_App_Final_Project wefly-app@${{ secrets.SERVER_IP }}:/synrgy
      - name: Execute deploy script
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} wefly-app@${{ secrets.SERVER_IP }} 'bash /synrgy/deploy_script.sh'